# Generated by Django 4.1.1 on 2022-09-17 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='torq.car')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil', models.PositiveIntegerField()),
                ('transmission_oil', models.PositiveIntegerField()),
                ('differential_oil', models.PositiveIntegerField()),
                ('coolant', models.PositiveIntegerField()),
                ('brake_fluid', models.PositiveIntegerField()),
                ('brake_pads', models.PositiveIntegerField()),
                ('brake_rotor', models.PositiveIntegerField()),
                ('engine_air_filter', models.PositiveIntegerField()),
                ('cabin_air_filter', models.PositiveIntegerField()),
                ('fuel_filter', models.PositiveIntegerField()),
                ('tires', models.PositiveIntegerField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='torq.car')),
            ],
        ),
    ]
