# Generated by Django 4.1.1 on 2022-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
