# Generated by Django 4.1.1 on 2022-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0002_alter_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
