# Generated by Django 4.1.1 on 2022-09-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0003_alter_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
