# Generated by Django 4.1.1 on 2022-09-16 06:45

from django.db import migrations, models
import torq.models


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0004_remove_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=torq.models.upload_to),
        ),
    ]
