# Generated by Django 4.1.1 on 2022-09-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torq', '0005_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
